/* ======================================================
   STAGE 2 — Single Program Customer Onboarding (12 emails)
   Speaking & Authorship Collection
   4 programs x 3 emails: 7 Figure Creator, Course Pro, Speak and Inspire, Stage Effect
   ====================================================== */

Object.assign(window.EMAIL_DATA, {

// ================================================================
// 7 FIGURE CREATOR — Onboarding (3 emails)
// ================================================================

'ob-7fc-1': {
    subject: 'Welcome to 7 Figure Creator -- your creator journey starts now',
    preheader: 'Your login is ready. Here is exactly what to expect and where to begin.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1818x1022/9cfa71b698/trainer_john-lee_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Commitment',
    cta: 'Log In & Start \u2192', url: 'https://www.mindvalley.com/membership/7-figure-creator',
    body: 'Hey there,\n\nCongratulations. You just joined 7 Figure Creator -- and that decision says something important about who you are.\n\nYou are not someone who consumes content endlessly without acting. You are someone who invests in the system that turns expertise into income.\n\n**Your program is live in your account. Let me walk you through what you have.**\n\n---\n\n**What You Now Have Access To:**\n\n--> **The complete 7 Figure Creator curriculum** with John Lee -- from content creation to algorithms to sales funnels to scaling\n--> **Daily lessons designed for 15-20 minutes** -- structured so you can build your creator business without quitting your day job\n--> **A proven system** used by the man who went from 0 to 6 million followers in 3.5 years\n\n---\n\n**What To Expect:**\n\nThe program is structured as a journey. You will not be overwhelmed with everything at once.\n\n--> **Week 1:** Master the fundamentals of content creation -- what makes content go viral, how to craft your message, and how to find your niche\n--> **Week 2:** Learn the algorithm -- how platforms work, what they reward, and how to get your content seen by the right people\n--> **Week 3:** Build your monetization engine -- how to turn attention into income streams that scale\n--> **Week 4:** The growth flywheel -- how to create compounding growth that works while you sleep\n\nEach lesson builds on the last. By the end, you will have a complete system -- not just knowledge, but a working plan.\n\n---\n\n**Where To Start:**\n\nLog in. Open Lesson 1. Press play. It takes 15 minutes.\n\nDo not overthink it. Do not wait for the perfect moment. The people who build 7-figure creator businesses are the ones who start.\n\n**[Log In & Start Your First Lesson \u2192](https://www.mindvalley.com/membership/7-figure-creator)**\n\n---\n\nTo your creator journey,\n\n[Signature]\n\nP.S. Tomorrow, I will share one of the most powerful techniques from the program -- a single insight that changes how you think about content creation forever. But first, get that first lesson done. Everything builds from here.'
},

'ob-7fc-2': {
    subject: 'The one thing every 7-figure creator does differently',
    preheader: 'It is not about posting more content. It is about this one strategic shift.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1818x1022/9cfa71b698/trainer_john-lee_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Reciprocity',
    cta: 'Start First Lesson \u2192', url: 'https://www.mindvalley.com/membership/7-figure-creator',
    body: 'Hey there,\n\nNow that you have started 7 Figure Creator, I want to share one of the most powerful shifts John Lee teaches early in the program.\n\nMost aspiring content creators think the formula is simple: **create more content = get more followers = make more money.**\n\nIt sounds logical. But it is wrong.\n\n---\n\n**Here is what 7-figure creators actually do differently:**\n\nThey do not create content. **They create systems that produce content.**\n\nThere is a massive difference.\n\nCreating content is reactive. You sit down, think of something to post, record it, hope it works, repeat tomorrow. It is exhausting. It is inconsistent. And it leads to burnout within months.\n\n**Creating a content system is strategic.** You design a repeatable process:\n\n--> A content pillar framework that ensures every post serves a purpose\n--> A batch creation workflow that produces a week of content in one session\n--> A distribution strategy that puts your content in front of the right people on the right platforms\n--> A feedback loop that tells you what is working so you can double down\n\nJohn went from 0 to 6 million followers not because he posted more than everyone else. **He posted smarter.** He had a system that turned every piece of content into a strategic asset.\n\n---\n\n**The Content Pillar Framework:**\n\nThis is one of the first things you will learn in the program. Instead of asking "what should I post today?" you build 3-5 content pillars -- core themes that your audience cares about.\n\nEvery piece of content you create falls into one of those pillars. This means:\n\n--> You never run out of ideas (the pillars generate infinite topics)\n--> Your content is consistent and recognizable (your audience knows what to expect)\n--> You build authority in specific areas (instead of being a generalist nobody remembers)\n\n---\n\nThis is just Day 2 of the program. The techniques get more powerful from here.\n\nLog in and continue your journey. The system is waiting for you.\n\n**[Continue Your Lessons \u2192](https://www.mindvalley.com/membership/7-figure-creator)**\n\nTo your creator system,\n\n[Signature]\n\nP.S. The difference between a hobbyist creator and a 7-figure creator is not talent or luck. It is having a system. You are building yours right now. Keep going.'
},

'ob-7fc-3': {
    subject: 'The compound effect of daily creator practice',
    preheader: 'Day 3 insight: why the creators who win are the ones who build one habit.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1818x1022/9cfa71b698/trainer_john-lee_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Social Proof',
    cta: 'Continue Your Journey \u2192', url: 'https://www.mindvalley.com/membership/7-figure-creator',
    body: 'Hey there,\n\nDay 3 of your 7 Figure Creator journey. Let me share something that separates the creators who build sustainable businesses from the ones who flame out.\n\n**It is not the big viral moment. It is the daily 15-minute habit.**\n\n---\n\nHere is the math that most aspiring creators miss:\n\n--> 15 minutes per day = 91 hours of focused creator training per year\n--> 91 hours of strategic practice = more training than most MBA programs give in an entire semester on content marketing\n--> Compound that over 12 months, and you have built an asset -- a body of content, a growing audience, and a monetization engine -- that works even while you sleep\n\nJohn Lee did not build 6 million followers in one viral explosion. He built them through **consistent, strategic daily practice** over 3.5 years.\n\n---\n\n**What Other 7 Figure Creator Members Report by Day 3:**\n\n--> "I finally understand why my previous content did not work. It was not bad -- it just was not strategic."\n--> "The content pillar framework alone saved me hours of \'what should I post today?\' anxiety."\n--> "I can already see the shape of my creator business. It feels real now, not like a dream."\n\nThese are typical Day 3 shifts. The real breakthroughs start in Week 2 when you begin applying the algorithm insights.\n\n---\n\n**Your habit for today:**\n\nLog in. Complete today\'s lesson. It takes 15 minutes.\n\nThat is it. Not a heroic effort. Not a 4-hour content creation marathon. Just 15 minutes of strategic learning from someone who has done exactly what you want to do.\n\nThe creators who build 7-figure businesses are not the most talented. They are the most consistent.\n\n**[Continue Your Journey \u2192](https://www.mindvalley.com/membership/7-figure-creator)**\n\nRooting for you,\n\n[Signature]\n\nP.S. You are three days in. The foundation is forming. By the end of this week, you will have more clarity on your creator business than most people get in months of scattered YouTube tutorials and guesswork. Stay the course.'
},

// ================================================================
// COURSE PRO — Onboarding (3 emails)
// ================================================================

'ob-cp-1': {
    subject: 'Welcome to Course Pro -- your first course starts here',
    preheader: 'Jimmy Naraine and Vishen are your guides. Here is what to expect in the next 30 days.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/f2007863a8/cp_lp_signup_top_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Commitment',
    cta: 'Log In & Start \u2192', url: 'https://www.mindvalley.com/membership/course-pro',
    body: 'Hey there,\n\nWelcome to Course Pro. You just made a decision that most aspiring course creators never make -- you invested in the system instead of hoping for the best.\n\n**Your program is live. Let me show you what you have.**\n\n---\n\n**What You Now Have Access To:**\n\n--> **The complete Course Pro curriculum** with Jimmy Naraine and Vishen -- from idea validation to recording to launch to promotion\n--> **A 30-day structured journey** -- daily lessons designed to get you from "I have an idea" to "I have a published course"\n--> **Proven frameworks** from one of the world\'s top Udemy instructors (350,000+ students, 33,000+ five-star ratings) and the founder of the world\'s largest personal growth platform\n\n---\n\n**The 30-Day Roadmap:**\n\n--> **Week 1: Mindset and Validation** -- overcome the "I am not ready" illusion, validate your course idea, and define your unique transformation\n--> **Week 2: Design and Structure** -- build your curriculum using the transformation formula, organize lessons for maximum impact\n--> **Week 3: Production** -- go from camera shy to magnetic presenter, record your lessons with confidence, create professional-quality content on any budget\n--> **Week 4: Launch and Promote** -- publish your course, implement the promotion playbook, and start enrolling students\n\n---\n\n**Where To Start:**\n\nLesson 1 tackles the biggest barrier: the belief that you are not ready. Jimmy calls it "the stubborn illusion." Within 15 minutes, you will experience a mindset shift that vaporizes the doubt.\n\nDo not skip it. Everything else builds on this foundation.\n\n**[Log In & Start Lesson 1 \u2192](https://www.mindvalley.com/membership/course-pro)**\n\n---\n\nTo your first course,\n\n[Signature]\n\nP.S. 30 days from now, you could have a published online course. Not in theory -- in practice. Jimmy\'s system has helped hundreds of thousands of students do exactly this. Tomorrow, I will share the single most powerful technique for overcoming camera anxiety. It works overnight.'
},

'ob-cp-2': {
    subject: 'The camera confidence trick that works overnight',
    preheader: 'Simple shifts in posture, tone, and gestures that make you magnetic on screen.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/f2007863a8/cp_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Reciprocity',
    cta: 'Start First Lesson \u2192', url: 'https://www.mindvalley.com/membership/course-pro',
    body: 'Hey there,\n\nNow that you have started Course Pro, let me share one of the techniques that surprises people the most.\n\n**Being good on camera is not a talent.** It is not even a skill that takes years to master. It is a set of simple, specific adjustments to your posture, tone of voice, and hand gestures that you can implement TODAY.\n\n---\n\n**Here is what Jimmy teaches (and what I have seen work with thousands of course creators):**\n\n**1. The Posture Reset**\nMost people slouch on camera without realizing it. This subconsciously signals low confidence to your audience. The fix: sit up straight, lean slightly forward (about 5 degrees), and keep your shoulders back. This single adjustment changes how authoritative you appear.\n\n**2. The Tone Triangle**\nMonotone kills engagement. Jimmy teaches a technique where you vary your tone in a triangular pattern -- authoritative statement, curious question, warm encouragement. This pattern mimics natural, engaging conversation and keeps your audience hooked.\n\n**3. The Hand Gesture Rule**\nKeep your hands visible and use deliberate gestures to emphasize key points. Studies show that speakers who use hand gestures are perceived as more trustworthy, more competent, and more engaging.\n\n---\n\n**The Overnight Part:**\n\nHere is why this works so fast. Camera confidence is not about BECOMING a different person. It is about REMOVING the awkwardness that comes from not knowing what to do with your body.\n\nOnce you have a specific physical protocol -- sit this way, speak this way, move your hands this way -- the awkwardness disappears. And underneath it, your natural charisma emerges.\n\nMost Course Pro members report feeling dramatically more comfortable on camera after just one practice session using these techniques.\n\n---\n\nLog in and continue your journey. Today\'s lesson goes deeper into the production techniques that turn these principles into your default state.\n\n**[Continue Your Lessons \u2192](https://www.mindvalley.com/membership/course-pro)**\n\nTo your confidence on camera,\n\n[Signature]\n\nP.S. Jimmy went from a Goldman Sachs cubicle to recording courses in 76 countries. He was not born charismatic on camera -- he learned these exact adjustments. And then he taught them to 350,000+ students. You are next.'
},

'ob-cp-3': {
    subject: 'The transformation formula (why your course will actually work)',
    preheader: 'Day 3 insight: You do not need to be the best in your field. You need this formula.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/f2007863a8/cp_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Social Proof',
    cta: 'Continue Your Journey \u2192', url: 'https://www.mindvalley.com/membership/course-pro',
    body: 'Hey there,\n\nDay 3 of Course Pro. Today I want to address something that might still be nagging at you, even after starting the program.\n\n**"Am I really qualified to teach this?"**\n\nLet me share what Jimmy and I have learned after collectively helping millions of students learn online.\n\n---\n\n**You do not need to be the best in your field.** You need to be 2-3 steps ahead of your student.\n\nThink about it. When you were learning to ride a bike, you did not need an Olympic cyclist to teach you. You needed your older sibling who had figured it out last summer. Someone close enough to your experience to understand your fear, but far enough ahead to show you the way.\n\n**That is the Transformation Formula:**\n\n--> **Start with the student\'s current pain** -- the specific frustration, confusion, or desire they have right now\n--> **Map the transformation** -- the clear, specific outcome they will achieve by the end of your course\n--> **Fill the gap** -- your unique knowledge, frameworks, and experience that bridge the distance between their pain and their desired outcome\n\n---\n\n**Why This Matters More Than Credentials:**\n\nJimmy was not the world\'s leading expert in any single topic when he launched his first course. He was someone who had figured out something useful and could explain it clearly.\n\n--> 350,000+ students later\n--> 33,000+ five-star ratings later\n--> Featured in Forbes, Entrepreneur, and Business Insider\n\n**The Transformation Formula is what makes courses succeed -- not credentials, not fame, not being the best.**\n\n---\n\n**What Other Course Pro Members Say By Day 3:**\n\n--> "I finally realized I DO have enough to teach. The transformation formula made it click."\n--> "I mapped out my first course in 20 minutes using this framework. It felt so clear."\n--> "The mindset shift from Day 1 combined with this formula -- I actually believe this is going to work."\n\nLog in. Complete today\'s lesson. The transformation formula gets applied in practice today.\n\n**[Continue Your Journey \u2192](https://www.mindvalley.com/membership/course-pro)**\n\nRooting for your course,\n\n[Signature]\n\nP.S. 27 days from now, you will have a published course. Not because of talent or luck -- because of a system that has worked for hundreds of thousands of people. Trust the process. Day 3 is where it starts to click.'
},

// ================================================================
// SPEAK AND INSPIRE (Lisa Nichols) — Onboarding (3 emails)
// ================================================================

'ob-si-1': {
    subject: 'Welcome to Speak and Inspire -- your voice matters',
    preheader: 'Lisa Nichols is your guide. Here is what to expect and where to begin.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/66d8d0bda3/sai_lp_signup_top_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Commitment',
    cta: 'Log In & Start \u2192', url: 'https://www.mindvalley.com/membership/speak-and-inspire',
    body: 'Hey there,\n\nWelcome to Speak and Inspire with Lisa Nichols.\n\nI want to start by telling you something Lisa would say if she were writing this email herself:\n\n**"Your story is not your shame. Your story is your superpower."**\n\nThat is the foundation of everything you are about to learn. And it is going to change how you think about your voice, your message, and your ability to move people.\n\n---\n\n**What You Now Have Access To:**\n\n--> **The complete Speak and Inspire curriculum** with Lisa Nichols -- the world\'s most renowned speaking and communication coach\n--> **Daily lessons designed for 15-20 minutes** -- each one building your ability to tell stories, connect with audiences, and inspire action\n--> **Techniques used by a woman who went from $11.42 in her bank account to commanding stages worldwide** and being featured on Oprah, The Steve Harvey Show, and The Today Show\n\n---\n\n**What To Expect:**\n\n--> **The Mess to Message Framework** -- Lisa\'s signature technique for turning your personal struggles into your most powerful communication tool. This alone has changed thousands of speakers\' careers.\n--> **Story-Showing (not Story-Telling)** -- the technique that makes audiences SEE and FEEL your stories, not just hear them\n--> **The Connection Method** -- how to deeply connect with any audience, whether one person or 1,000\n--> **Hollywood\'s 10-Second Rule** -- the instant impression technique that makes you unforgettable\n\n---\n\n**Where To Start:**\n\nLesson 1 begins with the most important question: **What is your story?**\n\nNot the polished, LinkedIn-ready version. The real one. The messy, uncomfortable, deeply human one.\n\nBecause that is where your power lives.\n\nLog in. Press play. Let Lisa guide you.\n\n**[Log In & Start Your Journey \u2192](https://www.mindvalley.com/membership/speak-and-inspire)**\n\n---\n\nTo your voice,\n\n[Signature]\n\nP.S. Lisa\'s outreach program has prevented over 3,800 teen suicides. That is the power of knowing how to speak with authenticity and heart. Tomorrow, I will share the Mess to Message framework -- the single technique that started it all for her.'
},

'ob-si-2': {
    subject: 'The Mess to Message framework (Lisa Nichols\' signature technique)',
    preheader: 'Your deepest pain is your greatest communication asset. Here is how to use it.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/66d8d0bda3/sai_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Reciprocity',
    cta: 'Start First Lesson \u2192', url: 'https://www.mindvalley.com/membership/speak-and-inspire',
    body: 'Hey there,\n\nNow that you have started Speak and Inspire, I want to unpack the technique that sits at the heart of everything Lisa teaches.\n\n**The Mess to Message Framework.**\n\n---\n\nHere is what most people get wrong about speaking:\n\nThey try to appear polished. Professional. Put-together. They hide their struggles and lead with their achievements.\n\n**And their audiences feel nothing.**\n\nBecause human beings do not connect with perfection. We connect with vulnerability. We connect with struggle. We connect with the raw, honest truth of what someone has been through.\n\n---\n\n**Lisa\'s Mess to Message framework works like this:**\n\n**Step 1: Identify your "mess"** -- the hardest moment, the lowest point, the experience you might normally hide. For Lisa, it was wrapping her baby in a towel because she could not afford diapers.\n\n**Step 2: Find the turning point** -- the moment when something shifted. When you decided "never again" or "I choose differently." This is the pivot of your story.\n\n**Step 3: Extract the universal truth** -- the lesson inside your specific experience that applies to everyone. For Lisa: "Your circumstances do not define your capacity."\n\n**Step 4: Frame it as a mission** -- your mess becomes your message becomes your mission. You do not just tell people what happened. You inspire them to join a cause.\n\n---\n\n**Why This Is So Powerful:**\n\nWhen you speak from your mess, three things happen:\n\n--> **Trust forms instantly.** Your audience feels safe because you went first with vulnerability.\n--> **Connection deepens.** People see themselves in your story -- their own struggles reflected in yours.\n--> **Action follows.** When someone feels deeply connected to your message, they do not just listen. They MOVE.\n\nThis is why Lisa\'s Steve Harvey Show appearance hit 40+ million views. She did not perform. She shared her mess. And millions of people felt it in their bones.\n\n---\n\nToday\'s practice:\n\nThink about your "mess." The story you have been hiding. The experience you downplay.\n\nNow imagine telling it with the framework above.\n\nThat is today\'s lesson. Log in and let Lisa walk you through it.\n\n**[Continue Your Lessons \u2192](https://www.mindvalley.com/membership/speak-and-inspire)**\n\nTo your most authentic voice,\n\n[Signature]\n\nP.S. Every great speaker has a "mess" that became their message. MLK Jr. had the weight of injustice. Brene Brown had the shame of vulnerability research. Lisa had $11.42 and a towel. What is yours? Today\'s lesson helps you find it.'
},

'ob-si-3': {
    subject: 'The daily voice practice that compounds (Day 3 of Speak and Inspire)',
    preheader: 'Story-showing, the 10-second rule, and why Day 3 is where the shift happens.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/66d8d0bda3/sai_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Social Proof',
    cta: 'Continue Your Journey \u2192', url: 'https://www.mindvalley.com/membership/speak-and-inspire',
    body: 'Hey there,\n\nDay 3 of Speak and Inspire. Something is already shifting.\n\nYou may not have words for it yet. But the way you think about your story, your voice, and your ability to connect with people is already different from three days ago.\n\nHere is what I want you to know: **that shift is real. And it compounds.**\n\n---\n\n**What Other Speak and Inspire Members Report by Day 3:**\n\n--> "I told my mess-to-message story to a friend. She cried. I cried. It was the most connected conversation I have had in years."\n--> "I used the 10-second rule in a meeting today. Everyone leaned in. My boss noticed."\n--> "For the first time, I do not feel ashamed of my story. I feel powerful because of it."\n\nThese are not exceptional results. They are typical Day 3 outcomes. The exceptional results come in Week 2 when story-showing fully activates.\n\n---\n\n**Story-Showing vs Story-Telling:**\n\nThis is the technique that separates good speakers from unforgettable ones.\n\n**Story-telling** is narration: "I was broke, living on a couch, and feeling hopeless."\n\n**Story-showing** is immersion: "Picture this. A kitchen counter in South Central L.A. One towel. One baby. And $11.42 on a bank statement that I keep re-reading because maybe -- maybe -- I missed a zero."\n\nDo you feel the difference? Story-showing puts your audience INSIDE the moment. They see the kitchen. They feel the towel. They hear the silence of a mother calculating whether she can afford diapers.\n\n**Lisa teaches you exactly how to do this.** It is not magic. It is technique.\n\n---\n\n**Your Daily Practice:**\n\nSpend 15 minutes with today\'s lesson. Then take one story from your life -- any story -- and practice telling it as a "story show" instead of a "story tell."\n\nAdd the sensory details. The specific numbers. The physical setting. The emotion you felt in your body.\n\nThis daily practice, compounded over the full program, transforms how every person in your life experiences your communication.\n\n**[Continue Your Journey \u2192](https://www.mindvalley.com/membership/speak-and-inspire)**\n\nProud of you for being here,\n\n[Signature]\n\nP.S. Lisa went from a woman who believed her voice did not matter to someone compared alongside MLK Jr., JFK, and Mandela as one of history\'s greatest orators. The difference was daily practice with these exact techniques. Keep going. Day 3 is where it starts to click.'
},

// ================================================================
// STAGE EFFECT (Eric Edmeades) — Onboarding (3 emails)
// ================================================================

'ob-se-1': {
    subject: 'Welcome to The Stage Effect -- your 21-day transformation begins',
    preheader: 'Eric Edmeades is your guide. From foundation to magical presentations in 21 days.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1920x1080/6f3157d965/tse-solution.jpg',
    schwartz: 'Most-Aware', cialdini: 'Commitment',
    cta: 'Log In & Start \u2192', url: 'https://www.mindvalley.com/membership/stage-effect',
    body: 'Hey there,\n\nWelcome to The Stage Effect with Eric Edmeades.\n\nYou just made a decision that puts you in rare company. Most people dream about being great speakers. You decided to actually become one.\n\n**Your 21-day transformation is live in your account.**\n\n---\n\n**What You Now Have Access To:**\n\n--> **A complete 21-day program** -- 5-20 minutes per day -- designed by a man with 10,000+ hours of stage time\n--> **Eric\'s 3-pillar system:** Storytelling Mastery, Presentation Mechanics, Stage Presence & Charisma\n--> **Techniques trusted by PWC, Google, Facebook, Cisco, ExxonMobil, and Salesforce**\n\n---\n\n**Your 21-Day Roadmap:**\n\n--> **Part 1 (Days 1-5): Lay the Foundation** -- learn the principles of an unforgettable presentation. What makes audiences lean in. What makes them check their phones. And the critical difference between the two.\n--> **Part 2 (Days 6-10): Master Storytelling** -- the primary operating language of the mind. Eric breaks down the exact narrative structures that captivate human attention.\n--> **Part 3 (Days 11-16): Design Your Presentation** -- Eric\'s blueprint for creating any successful presentation from scratch. Any topic. Any audience. Any format.\n--> **Part 4 (Days 17-21): Present Magically** -- stage presence, energy transfer, charisma. The final piece that makes everything come alive.\n\n---\n\n**Where To Start:**\n\nDay 1 is about foundation. Not technique -- foundation. Eric starts with WHY people listen. What the brain actually pays attention to. And the single biggest mistake that kills 90% of presentations in the first 15 seconds.\n\nThis is not filler. This is the foundation that everything else is built on.\n\nLog in. Day 1. 5-20 minutes. Go.\n\n**[Log In & Start Day 1 \u2192](https://www.mindvalley.com/membership/stage-effect)**\n\n---\n\nTo your stage mastery,\n\n[Signature]\n\nP.S. Eric went from homeless teenager to touring with Tony Robbins and Richard Branson. He did not start with talent. He started with a system. In 21 days, you will have that system too. Tomorrow, I will share the 15-Second Hook -- the technique that makes or breaks every presentation.'
},

'ob-se-2': {
    subject: 'The 15-Second Hook (your audience decides this fast)',
    preheader: 'Eric Edmeades\' technique for commanding attention from your very first words.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1920x1080/6f3157d965/tse-solution.jpg',
    schwartz: 'Product-Aware', cialdini: 'Reciprocity',
    cta: 'Continue Your Lessons \u2192', url: 'https://www.mindvalley.com/membership/stage-effect',
    body: 'Hey there,\n\nNow that you have started The Stage Effect, I want to share one of Eric\'s most powerful concepts.\n\n**Your audience decides in 15 seconds whether to pay attention or check out.**\n\nFifteen seconds. That is it. Not five minutes of warming up. Not a gradual build. Fifteen seconds.\n\n---\n\n**What most speakers do in their first 15 seconds:**\n\n--> "Hi, my name is... and today I will be talking about..."\n--> "Thank you so much for having me, it is such an honor to be here..."\n--> "So, um, let me start by telling you a little about my background..."\n\nEvery single one of those openings tells the audience: "You can safely check your phone now."\n\n---\n\n**What Eric teaches instead -- The 15-Second Hook:**\n\nYour first 15 seconds need to do one thing: **create an open loop in the audience\'s mind.**\n\nAn open loop is a question, a mystery, or a tension that the brain NEEDS to resolve. Until it is resolved, the audience cannot look away.\n\nExamples:\n\n--> "At 15 years old, I was sleeping on the street. By 35, I was sharing a stage with Tony Robbins. And the difference was one conversation that lasted 90 seconds." (Now the audience HAS to know what that conversation was.)\n\n--> "There is a technique so powerful that Google, Facebook, and Salesforce pay me to teach it to their teams. It takes 30 seconds to learn. And you will know it before you leave this room." (Now they are waiting for the technique.)\n\n--> "The worst presentation I ever gave made me $50,000. Let me tell you why." (Now they need to understand the paradox.)\n\n---\n\n**The Energy Transfer:**\n\nBut the 15-Second Hook is not just about words. Eric teaches that communication is energy transfer. The energy you bring in those first 15 seconds sets the frequency for the entire presentation.\n\nConfident energy in the first 15 seconds = the audience trusts you for the next 45 minutes.\nHesitant energy in the first 15 seconds = the audience is looking for exits.\n\nToday\'s lesson goes deeper into how to build and deliver your hook with the right energy.\n\n**[Continue Your Lessons \u2192](https://www.mindvalley.com/membership/stage-effect)**\n\nTo your commanding presence,\n\n[Signature]\n\nP.S. Practice this today. Your next meeting, conversation, or even social media video -- open with an open loop. Watch what happens to the other person\'s attention. The 15-Second Hook works everywhere, not just on stage.'
},

'ob-se-3': {
    subject: 'Eliminate stage fright permanently (Day 3 technique)',
    preheader: 'Eric\'s authentic persona method turns nervousness into your greatest asset on stage.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1920x1080/6f3157d965/tse-solution.jpg',
    schwartz: 'Product-Aware', cialdini: 'Social Proof',
    cta: 'Continue Your Journey \u2192', url: 'https://www.mindvalley.com/membership/stage-effect',
    body: 'Hey there,\n\nDay 3 of The Stage Effect. Today, let me address the thing that stops more potential speakers than anything else.\n\n**Stage fright.**\n\nThe racing heart. The sweaty palms. The voice that shakes. The mind that goes blank. The overwhelming urge to be anywhere else.\n\nHere is what Eric says about it -- and it might surprise you.\n\n---\n\n**"Stage fright is not your enemy. It is misunderstood energy."**\n\nThe physical sensations of stage fright -- elevated heart rate, adrenaline, heightened awareness -- are identical to the physical sensations of excitement.\n\n**Your body cannot tell the difference.** Only your mind labels it as "fear."\n\nEric\'s approach does not try to eliminate the sensation. It teaches you to **relabel and redirect it.**\n\n---\n\n**The Authentic Persona Method:**\n\n--> **Step 1: Acknowledge the energy.** Do not fight it. Do not pretend it is not there. Say to yourself: "I feel energy. Good. That means I care about what I am about to say."\n\n--> **Step 2: Ground it physically.** Plant your feet. Feel the floor. Take one deep breath that fills your belly, not your chest. This activates your parasympathetic nervous system and shifts you from reactive to responsive.\n\n--> **Step 3: Channel it through your authentic persona.** Eric teaches that every great speaker has an "authentic persona" -- the version of themselves that is fully present, fully engaged, and fully confident. Not a performance. Not an act. YOUR energy at its highest expression.\n\nThe authentic persona is not something you create. It is something you UNCOVER. It is already inside you. Stage fright is just the static covering the signal.\n\n---\n\n**What Stage Effect Members Report By Day 3:**\n\n--> "I gave a team presentation today using the 15-Second Hook and the grounding technique. My hands did not shake for the first time in years."\n--> "The reframe from fear to energy changed everything. Same sensations, completely different experience."\n--> "I am starting to actually look FORWARD to speaking opportunities instead of dreading them."\n\n90% of Eric\'s students report being more confident on stage by the end of the program. But many report feeling the shift as early as Day 3.\n\n---\n\nToday\'s lesson takes you deeper into the authentic persona method. Log in and continue.\n\n**[Continue Your Journey \u2192](https://www.mindvalley.com/membership/stage-effect)**\n\nTo your fearless voice,\n\n[Signature]\n\nP.S. Eric has 10,000+ hours on stage. He still feels the energy before every talk. The difference? He knows it is fuel, not fear. That reframe alone can transform your entire relationship with speaking. Keep going.'
}

});
