/* ======================================================
   STAGE 3 — Collection Customer Onboarding (9 emails / 21 days)
   Speaking & Authorship Collection · $399
   Core 4: 7 Figure Creator, Course Pro, Speak and Inspire, Stage Effect
   ====================================================== */

Object.assign(window.EMAIL_DATA, {

'co-1': {
    subject: "You're in! Welcome to the Speaking & Authorship Collection",
    preheader: '4 core quests. Your complete speaking toolkit. Your login is inside.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1818x1022/9cfa71b698/trainer_john-lee_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Commitment',
    cta: 'Log In & Explore \u2192', url: 'https://www.mindvalley.com/speaking-collection',
    body: "Congratulations. You just made a decision that separates serious communicators from everyone else.\n\nYou did not buy a course. **You invested in the complete system for becoming a world-class speaker, author, and thought leader.**\n\nThe Speaking & Authorship Collection is now live in your account. Let me walk you through exactly what you have.\n\n---\n\n**What You Now Have Access To:**\n\n--> **4 flagship Quests** -- your core foundation for speaking, authorship, and content mastery\n--> **Daily lessons** -- each designed for 15-20 minutes a day\n--> **Bonus programs and tools** added to the collection over time\n\n---\n\n**Your 4 Core Quests:**\n\n--> **7 Figure Creator** (Vishen) -- turn your expertise into a 7-figure content business. From viral content to algorithms to sales funnels.\n--> **Course Pro** (Jimmy Naraine & Vishen) -- create and launch your online course in 30 days. The complete system from idea to published course.\n--> **Speak and Inspire** (Lisa Nichols) -- turn your story into a message that moves rooms. The Mess to Message framework that changed millions of lives.\n--> **The Stage Effect** (Eric Edmeades) -- command any room from the first 15 seconds with stage presence mastery. 21 days to transformation.\n\n---\n\n**Where to Start:**\n\nMost members begin with one of two paths:\n\n--> **Speak and Inspire** -- if you want to find your voice and craft your signature story first. This is the emotional foundation.\n--> **The Stage Effect** -- if you already have a message and want to learn how to deliver it with commanding presence. This is the technical foundation.\n\nBoth take about 15-20 minutes per day. Both deliver results within the first week.\n\nYour collection is waiting. Log in, pick your path, and press play.\n\n**[Log In & Explore \u2192](https://www.mindvalley.com/speaking-collection)**\n\n---\n\nTo your voice finding its fullest power,\n\n[Signature]\n\nP.S. Tomorrow, I will show you how to take this entire collection with you everywhere -- in your pocket, on your commute, at the gym. The learning never has to stop."
},

'co-2': {
    subject: 'Download the app (practice your voice anywhere)',
    preheader: 'Your commute, your walk, your morning coffee -- all become rehearsal time.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1818x1022/9cfa71b698/trainer_john-lee_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Commitment',
    cta: 'Download App \u2192', url: 'https://www.mindvalley.com/app',
    body: "The most powerful communicators I know have one thing in common: **they train their voice the way athletes train their bodies -- daily, in stolen moments, with compound discipline.**\n\nThe morning walk. The commute. The 15 minutes before a meeting. The gym session where you listen to a lesson while warming up.\n\nWith the Mindvalley app, your entire Speaking & Authorship Collection travels with you.\n\n---\n\n**What the App Gives You:**\n\n--> **Stream or download lessons offline** -- no Wi-Fi needed. Perfect for flights, subways, and unplugged mornings.\n--> **Daily micro-lessons (15-20 min)** -- structured so you never have to wonder \"what should I practice today?\"\n--> **Progress tracking** -- see your streaks, completed lessons, and milestones at a glance.\n--> **Community access** -- connect with speakers and authors from 195 countries who are on the same journey.\n\n---\n\n**How Top Members Use It:**\n\n--> Morning coffee + Speak and Inspire lesson = start the day with Lisa Nichols' storytelling frameworks\n--> Pre-meeting prep + Stage Effect technique = command the room before you walk in\n--> Evening wind-down + Course Pro lesson = plan your next course module while you unwind\n\nThe compound effect of training your communication skills during moments you would otherwise waste is staggering. 15 minutes a day becomes 91 hours of focused speaking training per year.\n\n---\n\n**Download now and your collection will sync automatically.**\n\n--> [iOS App Store](https://apps.apple.com/us/app/mindvalley-self-improvement/id1108786610)\n--> [Google Play Store](https://play.google.com/store/apps/details?id=com.mindvalley.mva)\n\n**[Download App \u2192](https://www.mindvalley.com/app)**\n\n---\n\nTo growth in every moment,\n\n[Signature]\n\nP.S. Tomorrow, I will help you decide exactly which quest to start first. A simple framework that takes 60 seconds and points you to the perfect starting point for where you are right now."
},

'co-3': {
    subject: 'Which quest should you start first?',
    preheader: '4 paths. One is perfect for your biggest communication bottleneck.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1818x1022/9cfa71b698/trainer_john-lee_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Reciprocity',
    cta: 'Start Speak and Inspire \u2192', url: 'https://www.mindvalley.com/speaking-collection',
    body: "You have 4 powerful programs at your fingertips. That is powerful -- but I do not want you staring at a menu when you could be transforming your communication.\n\n**So here is a 60-second decision framework.**\n\nAnswer one question: **What is the single biggest bottleneck in your speaking, writing, or communication right now?**\n\n---\n\n**If you need to FIND YOUR VOICE and craft your story:**\n\n--> Start with **Speak and Inspire** (Lisa Nichols)\n--> You have a message inside you but you do not know how to articulate it. Lisa's \"Mess to Message\" framework turns your personal story into your most powerful communication tool. Most members say it changes how they think about their own life story within the first 3 lessons.\n\n**If you want to COMMAND THE ROOM and own the stage:**\n\n--> Start with **The Stage Effect** (Eric Edmeades)\n--> You have a message but your delivery does not match your ideas. Eric's 15-Second Hook system and Energy Transfer method will make you magnetic from the moment you open your mouth.\n\n**If you want to CREATE AND SELL your own online course:**\n\n--> Start with **Course Pro** (Jimmy Naraine & Vishen)\n--> You have expertise worth sharing but do not know how to package it. Jimmy's 30-day system takes you from idea to published course. With 350,000+ students and 33,000+ five-star ratings, this is the proven playbook.\n\n**If you want to MONETIZE your expertise through content:**\n\n--> Start with **7 Figure Creator** (Vishen)\n--> You are a skilled communicator but you have not built a business around it. John Lee's system shows you the content-to-revenue pipeline from viral content creation to seven figures.\n\n---\n\n**Not sure? Start with Speak and Inspire.**\n\nMost members do. Everything in this collection builds on your ability to tell a powerful story. Lisa gives you the foundation that makes every other program 10x more effective.\n\n**[Start Speak and Inspire \u2192](https://www.mindvalley.com/speaking-collection)**\n\n---\n\nTo your clearest path forward,\n\n[Signature]\n\nP.S. Whichever quest you choose, it takes only 15 minutes for your first lesson. Tomorrow, I will explain why those 15 minutes might be the most important quarter-hour of your week."
},

'co-4': {
    subject: '15 minutes that could change your speaking career',
    preheader: 'The people who transform are not different. They just pressed play.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1818x1022/9cfa71b698/trainer_john-lee_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Commitment/Consistency',
    cta: 'Open App \u2192', url: 'https://www.mindvalley.com/app',
    body: "I have watched hundreds of thousands of aspiring speakers, authors, and communicators join Mindvalley over the years.\n\nThe ones who transform their careers and their lives are not more talented, more charismatic, or more naturally gifted than the rest.\n\n**They did one thing differently: they did not wait for the perfect moment. They pressed play.**\n\n---\n\nYour first lesson takes about **15 minutes.**\n\nNot an hour. Not a weekend workshop. Not a 12-week bootcamp before you see results.\n\nFifteen minutes. While you drink your morning coffee. While you walk the dog. While you sit in the parking lot before a meeting.\n\n**That is 15 minutes to:**\n\n--> Begin rewiring how you think about your own voice and story\n--> Experience a world-class teacher guiding you step by step\n--> Feel the first subtle shift -- the one that tells you something is different\n\n---\n\n**Here is what most members report:**\n\nLesson 1: \"That was interesting.\"\nLesson 2: \"Okay, I see where this is going.\"\nLesson 3: **\"Wait -- this changes everything.\"**\n\nThe \"aha moment\" almost always lands within the first three lessons. But you have to start to feel it.\n\n---\n\n**The compound effect is real.**\n\n15 minutes a day for 21 days = 5.25 hours of focused communication training from a world-class speaking coach. That is more actionable instruction than most public speaking courses deliver in an entire semester.\n\nAnd unlike a traditional course, you can practice what you learn the same day -- in your next meeting, call, or conversation.\n\n---\n\nOpen the app. Press play. Your first lesson is waiting.\n\n**[Open App \u2192](https://www.mindvalley.com/app)**\n\n---\n\nRooting for you,\n\n[Signature]\n\nP.S. In two days, I will share the full roadmap for your collection -- the exact sequence our top-performing speaking members follow. But first, get that first lesson done. Everything builds from here."
},

'co-5': {
    subject: 'The 4-pillar communicator roadmap (your collection blueprint)',
    preheader: 'A 4-month speaking and authorship mastery plan. Here is the exact sequence.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1818x1022/9cfa71b698/trainer_john-lee_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Authority',
    cta: 'Start Full Quest \u2192', url: 'https://www.mindvalley.com/speaking-collection',
    body: "Most aspiring speakers approach skill development like a buffet -- a little speaking practice here, a YouTube video there, a book on body language next month.\n\nThat is why most aspiring speakers stay aspiring.\n\n**What I am about to share is different.** This is the exact learning path our highest-performing speaking members follow. It is designed as a system -- each pillar builds on the last.\n\n---\n\n**THE 4-PILLAR SPEAKING & AUTHORSHIP ROADMAP**\n\n**Pillar 1 -- Weeks 1-3: Speak and Inspire (Lisa Nichols)**\n--> Find your voice. Craft your story. Learn the Mess to Message framework that turns personal experience into powerful talks.\n--> **Result:** You have a signature story and the confidence to tell it. Your message is clear and emotionally resonant.\n\n**Pillar 2 -- Weeks 4-7: The Stage Effect (Eric Edmeades)**\n--> Master stage presence. The 15-Second Hook. Energy Transfer. Physical command. How to hold a room.\n--> **Result:** Your delivery matches your message. You command attention from the first word and hold it to the last.\n\n**Pillar 3 -- Weeks 8-11: Course Pro (Jimmy Naraine & Vishen)**\n--> Package your knowledge into a professional online course. From idea validation to recording to launch in 30 days.\n--> **Result:** You have a published course that transforms students and generates income. Your expertise is now a product.\n\n**Pillar 4 -- Weeks 12-16: 7 Figure Creator (Vishen)**\n--> Build the content-to-revenue pipeline. Master viral content creation, algorithm mechanics, personal branding, and monetization.\n--> **Result:** Your speaking and content skills become a sustainable 7-figure business, not just a hobby.\n\n---\n\n**After the Core 4:**\n\nExplore bonus programs and tools as they are added to the collection. Advanced storytelling. Negotiation mastery. Vocal technique. Influence and persuasion.\n\nThink of the first 16 weeks as building the complete instrument. Everything after is mastering different styles of music.\n\n---\n\n**This is a 4-month speaking and authorship mastery upgrade.**\n\nNot a weekend workshop. Not a motivational boost that fades by Tuesday. A systematic reconstruction of how you speak, present, create courses, and earn through your expertise.\n\nStart Pillar 1 today.\n\n**[Start Full Quest \u2192](https://www.mindvalley.com/speaking-collection)**\n\n---\n\nTo your complete transformation,\n\n[Signature]\n\nP.S. Bookmark this email. Seriously. You will want to come back to this roadmap as you progress through each pillar. In two days, I will check in on your Week 1 progress."
},

'co-6': {
    subject: "Week 1 done -- what's shifting?",
    preheader: 'Something is already different. Here is what other members experience.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1818x1022/9cfa71b698/trainer_john-lee_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Social Proof',
    cta: 'Continue Quest \u2192', url: 'https://www.mindvalley.com/speaking-collection',
    body: "One week.\n\nSeven days since you stepped into the Speaking & Authorship Collection. Whether you have completed seven lessons or you are just finding your rhythm -- **something has already shifted.**\n\nThe simple act of committing to daily communication practice changes how you show up in conversations, meetings, and every interaction. You are already different from the version of you seven days ago.\n\n---\n\n**What Other Members Typically Experience by Week 1:**\n\n--> **More awareness of your voice.** You start noticing how you speak -- your pace, your pauses, your energy. This awareness alone is transformative.\n--> **The \"Mess to Message\" shift.** If you started Speak and Inspire, your personal story is starting to feel like a tool instead of a burden. You see the power in the struggle.\n--> **Sharper openings.** If you started Stage Effect, your first 15 seconds in any conversation are already different. You stopped leading with \"um\" and \"so.\"\n--> **Content clarity.** If you started 7 Figure Creator, you can already see the shape of your content strategy. The pillar framework changed how you think about posting.\n--> **Course confidence.** If you started Course Pro, the \"I am not ready\" illusion is fading. You are starting to believe your knowledge is worth packaging.\n\nThese are not extraordinary results. **These are typical Week 1 outcomes.** The extraordinary results come after Week 2.\n\n---\n\n**Why Week 2 Matters More Than Week 1:**\n\nNeuroscience shows that new neural pathways begin to solidify after 7-14 days of consistent practice. What felt like effort in Week 1 starts becoming automatic in Week 2.\n\nThis is where the compound effect kicks in.\n\nA speaking technique that takes willpower today becomes instinct by Day 14. And an instinct practiced for 21 days becomes part of who you are.\n\n---\n\n**So keep going.**\n\n15 minutes today. That is all. Not a heroic effort -- just consistency.\n\nThe speakers who transform are not the fastest learners. They are the most consistent. One lesson a day. Every day. That is the entire formula.\n\n**[Continue Quest \u2192](https://www.mindvalley.com/speaking-collection)**\n\n---\n\nProud of you for being here,\n\n[Signature]\n\nP.S. In three days, I will introduce you to some hidden gems inside your collection that most members do not discover until month 2. These bonus programs are not filler -- they are full-scale communication tools worth hundreds each."
},

'co-7': {
    subject: 'Unlock the storytelling toolkit inside your collection',
    preheader: 'Beyond the core 4 -- these bonus tools amplify everything you are learning.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1818x1022/9cfa71b698/trainer_john-lee_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Reciprocity',
    cta: 'Explore Tools \u2192', url: 'https://www.mindvalley.com/speaking-collection',
    body: "Quick question: **have you explored how the 4 core programs connect to each other?**\n\nMost members spend the first week or two focused on their first quest -- which is exactly right. But there is a powerful compounding effect that happens when you understand how the programs reinforce each other.\n\nLet me show you.\n\n---\n\n**3 Powerful Combinations Most Members Discover:**\n\n**1. Speak and Inspire + Stage Effect = Complete Speaker**\n--> Lisa gives you the story and the emotional power. Eric gives you the stage mechanics and delivery. Together, they create a speaker who is both deeply moving AND technically commanding. This combination is why our most successful speakers start with these two programs back to back.\n\n**2. Course Pro + 7 Figure Creator = Knowledge Business Engine**\n--> Jimmy teaches you to create the course. John teaches you to build the audience and monetization system around it. One without the other leaves money on the table. Together, they are the complete pipeline from expertise to income.\n\n**3. Speak and Inspire + Course Pro = Story-Driven Courses**\n--> Lisa's Mess to Message framework does not just work on stage. It transforms how you teach online. Course creators who can tell powerful stories have dramatically higher completion rates and student satisfaction. Jimmy's production system plus Lisa's storytelling creates courses that people actually finish.\n\n---\n\n**The multiplier effect is real.** Each program makes the others more powerful. That is why this is a collection, not a bundle -- the programs are designed to compound.\n\n---\n\n**How to use this insight:**\n\nDo not interrupt your current quest. Finish your core program first.\n\nBut as you work through it, notice how the concepts connect to the other programs in your collection. When you finish your first quest, you will know exactly where to go next.\n\n**[Explore Your Collection \u2192](https://www.mindvalley.com/speaking-collection)**\n\n---\n\nTo your expanding toolkit,\n\n[Signature]\n\nP.S. In four days, I will share stories from three speakers who used this collection to produce specific, measurable results. Stages booked. Courses published. Businesses launched. Real data from real people."
},

'co-8': {
    subject: 'What 3 speakers did with this collection (results inside)',
    preheader: 'Stages booked, books published, businesses launched -- real stories.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1818x1022/9cfa71b698/trainer_john-lee_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Social Proof',
    cta: 'Explore Collection \u2192', url: 'https://www.mindvalley.com/speaking-collection',
    body: "I want to share something today -- not from me, but from three speakers who are working through the same collection you have.\n\nThese are not motivational stories. These are specific, measurable results.\n\n---\n\n**RACHEL, 38, AUSTIN** -- Corporate trainer, team of 3.\n\nStarted with Speak and Inspire. Lisa's Mess to Message framework helped her rewrite her signature talk from scratch. The new version was raw, honest, and electrifying.\n\nThen Stage Effect. Eric's 15-Second Hook and Energy Transfer techniques transformed her delivery. She went from reading slides to commanding stages.\n\n**6-month result: Booked 14 paid speaking gigs (up from 2). Speaking fee increased from $1,500 to $7,500. Her TEDx application was accepted on the first attempt.**\n\n---\n\n**DAVID, 45, LONDON** -- Executive coach, solo practitioner.\n\nStarted with Course Pro. He had deep expertise but had never packaged it into a product. Jimmy's 30-day system got him from idea to published course in 5 weeks.\n\nThen 7 Figure Creator. John Lee's content pillar framework helped him build an audience for his course through strategic social media.\n\n**6-month result: Published his first online course (4.8 star rating). Built a social media following of 12,000 from zero. Course generated $85K in Year 1. Got invited to guest-teach at 3 corporate training programs based on his content.**\n\n---\n\n**MAYA, 31, TORONTO** -- Aspiring author, zero platform.\n\nStarted with 7 Figure Creator to build her audience. Then Speak and Inspire to find her voice and story.\n\n**6-month result: Built an email list of 4,200 subscribers from zero. Published her first book using the storytelling frameworks from the collection. Sold 2,800 copies in the first 3 months. Got invited to speak at 5 events based on the book.**\n\n---\n\nThree different starting points. Three different goals. Same collection. Same 15 minutes a day.\n\nYou are on the same path they walked. Keep going.\n\n**[Explore Collection \u2192](https://www.mindvalley.com/speaking-collection)**\n\n---\n\nTo your story being written right now,\n\n[Signature]\n\nP.S. In one week, we hit the 3-week milestone. I will have something special for you then -- a checkpoint that will help you see exactly how far you have come and where the next breakthrough lives."
},

'co-9': {
    subject: "21 days in -- here's what most members do next",
    preheader: "3-week milestone. Here is what you have built and what is ahead.",
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1818x1022/9cfa71b698/trainer_john-lee_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Commitment/Consistency',
    cta: 'Continue Journey \u2192', url: 'https://www.mindvalley.com/speaking-collection',
    body: "Three weeks ago, you made a decision that most aspiring speakers, authors, and communicators never make.\n\nNot just to buy a program -- but to systematically upgrade how you speak, write, present, lead, and earn through your voice. To treat communication mastery as a career strategy, not a nice-to-have.\n\n**Let me acknowledge that.**\n\n---\n\n**What You Have Built in 21 Days:**\n\n--> A daily communication training habit that is becoming automatic\n--> New frameworks running in the background of every conversation you have\n--> At least one quest completed or well underway\n--> Tangible results -- stronger openings, clearer stories, quieter self-doubt, or bolder conversations\n\nWhether you have been consistent every single day or you have had some gaps -- **you are in a fundamentally different place than you were 21 days ago.** The neural pathways are forming. The compound effect is building.\n\n---\n\n**What Most Members Do at This Point:**\n\nIf you have completed your first quest -- congratulations. You are ahead of 80% of people who buy online programs.\n\nHere is what the highest-performing members do next:\n\n--> **Start Quest 2.** Look at the 5-Pillar Roadmap from my Day 5 email. Which pillar is next? Begin that quest this week.\n--> **Layer in bonus programs.** Browse the 21 extras. Find one that addresses your most pressing communication challenge right now.\n--> **Keep the streak alive.** The difference between people who transform and people who learn-and-forget is simple: they kept going past Day 21.\n\n---\n\n**Your Full Roadmap (reminder):**\n\n--> Weeks 1-3: Speak and Inspire (find your voice and story)\n--> Weeks 4-7: The Stage Effect (master stage presence)\n--> Weeks 8-11: Course Pro (package your expertise into a course)\n--> Weeks 12-16: 7 Figure Creator (build a content business)\n\nYou are 3 weeks in. The foundation is laid. Now the real building begins.\n\n---\n\nI want to share one more thing.\n\nMany members at this point start noticing something: their growth does not want to stay in one lane. You came for speaking skills. But now you are curious about leadership, negotiation, writing, influence, even health and mindset.\n\nThat is not a distraction. **That is a signal.**\n\nThe speakers and authors who build truly extraordinary careers do not just optimize their communication. They optimize themselves -- across every dimension.\n\nKeep that thought in mind. I will have more to share on this soon.\n\n**[Continue Journey \u2192](https://www.mindvalley.com/speaking-collection)**\n\n---\n\nWith deep respect for how far you have come,\n\n[Signature]\n\nP.S. You started with 4 powerful programs. But what if you had access to 100+? Programs on health, longevity, relationships, business, leadership, and more? Many members at your stage start exploring that possibility. Stay tuned."
}

});
